services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python3 manage.py runserver 0.0.0.0:8050
    container_name: fit_journal_backend
    volumes:
      - ./:/home/django/fit_journal/fit_journal
    ports:
      - "8050:8050"
    depends_on:
      - postgres
      - redis
    networks:
      - fit_journal_network

  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql@14/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-1234}
      - POSTGRES_DB=${POSTGRES_DB:-fit_journal_postgres}
    networks:
      - fit_journal_network

  redis:
    image: redis:7
    container_name: fit_journal_redis_cache
    restart: always
    networks:
      - fit_journal_network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  fit_journal_network:
    external: true
